name: Sync to Public Repo

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: 
      - "s3-sync"
    types:
      - completed
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read


    steps:
      - name: Generate GitHub App token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.SYNC_TO_PUBLIC_APP_ID }}
          private-key: ${{ secrets.SYNC_TO_PUBLIC_PRIVATE_KEY }}
          owner: daoninc
          repositories: |
            trustx-ootb-custom-pages

      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for full history

      - name: Push to public repo
        run: |
          git config --global user.email "daon-ci-bot@daon.com"
          git config --global user.name "daon-ci-bot"
          git clone https://daoninc:${{ steps.generate_token.outputs.token }}@github.com/daoninc/trustx-ootb-custom-pages.git
          cd trustx-ootb-custom-pages
          git remote add trustx-ootb-custom-pages https://daon-private/trustx-ootb-custom-pages.git
          git remote update
          git merge trustx-ootb-custom-pages/main
          git push origin main


