name: Sync to Public Repo

on:
  push:
  workflow_run:
    workflows: 
      - "s3-sync"
    types:
      - completed
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read


    steps:
      - name: Checkout the private repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for full history
          token: ${{ secrets.GH_AUTOMATION_BOT_PAT }}
          # path: trustx-ootb-custom-pages

      # - name: Checkout the public repo
      #   uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0  # needed for full history
      #     repository: daoninc/trustx-ootb-custom-pages-public
      #     token: ${{ secrets.GH_AUTOMATION_BOT_PAT }}
      #     path: trustx-ootb-custom-pages-public

      - name: Push to public repo
        run: |      
          git config --global user.name "daon-gh-automation-bot"
          git config --global user.email "gh-automation-bot@daon.com"
          git remote add public https://x-access-token:${{ secrets.GH_AUTOMATION_BOT_PAT }}@github.com/daoninc/trustx-ootb-custom-pages-public.git
          git push public main --force