name: Sync to Public Repo

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: 
      - "s3-sync"
    types:
      - completed
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read


    steps:
      - name: Generate GitHub App token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.SYNC_TO_PUBLIC_APP_ID }}
          private-key: ${{ secrets.SYNC_TO_PUBLIC_PRIVATE_KEY }}
          owner: daoninc
          repositories: |
            trustx-ootb-custom-pages

      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0  # needed for full history

      - name: Push to public repo
        run: |
          gh auth login --with-token <<<"$GITHUB_TOKEN"
          gh repo clone daoninc/trustx-ootb-custom-pages
          cd trustx-ootb-custom-pages
          git remote add upstream https://github.com/daon-private/trustx-ootb-custom-pages.git
          gh repo sync daoninc/trustx-ootb-custom-pages --source upstream --branch main


