name: Sync to Public Repo

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: 
      - "s3-sync"
    types:
      - completed
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read


    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for full history

      - name: Generate GitHub App token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.SYNC_TO_PUBLIC_APP_ID }}
          private-key: ${{ secrets.SYNC_TO_PUBLIC_PRIVATE_KEY }}
          owner: daoninc
          repositories: |
            trustx-ootb-custom-pages

      - name: Push to public repo
        env:
            GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          git config --global user.name "daon-ci-bot"
          git config --global user.email "daon-ci-bot@daon.com"
          git config --global credential.helper ""
          git remote remove public || true
          git remote add public https://x-access-token:${GH_TOKEN}@github.com/daoninc/trustx-ootb-custom-pages.git
          git remote -v
          git push --mirror public
